# 昇腾RAG系统配置文件

# 系统配置
system:
  name: "昇腾RAG系统"
  version: "1.0.0"
  debug: false
  log_level: "INFO"

# 服务器配置
server:
  api:
    host: "0.0.0.0"
    port: 8000
  web:
    host: "0.0.0.0"
    port: 8501

# 向量数据库配置
vector_store:
  type: "chroma"  # chroma 或 faiss
  persist_directory: "./data/vector_store"
  collection_name: "documents"
  
# 嵌入模型配置
embedding:
  model_name: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  model_path: "./models/embeddings"
  device: "cpu"  # cpu, cuda, npu
  batch_size: 32
  max_length: 512

# 大语言模型配置
llm:
  model_name: "chatglm3-6b"
  model_path: "./models/llm"
  device: "cpu"  # cpu, cuda, npu
  max_length: 2048
  temperature: 0.7
  top_p: 0.9

# 文档处理配置
document_processing:
  chunk_size: 500
  chunk_overlap: 50
  supported_formats:
    - ".txt"
    - ".md"
    - ".pdf"
    - ".docx"
    - ".xlsx"

# 检索配置
retrieval:
  top_k: 5
  similarity_threshold: 0.7
  rerank: true

# 昇腾NPU配置
ascend:
  enable: false
  device_id: 0
  precision: "fp16"
  
# 缓存配置
cache:
  enable: true
  ttl: 3600  # 秒
  max_size: 1000